- name: Create suer simone
  tags: always
  ansible.builtin.user:
    name: simone
    groups: root

- name: Add suoers file for simone
  tags: always
  ansible.builtin.copy:
    src: sudoer_simone
    dest: /etc/sudoers.d/simone
    owner: root
    group: root
    mode: "0440"

- name: Add ssh key for simone user
  tags: always
  ansible.posix.authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBAKXZZXlWGVNiNHtg1JWst2jXRTWvEWDO1Yr4t7k+3Y xtream@ubuntu-ws"
